window.PLAYLISTS = [
  {
    id: "special",
    name: "Midnight Runners",
    subtitle: "35 tracks · 9s crossfade",
    accent: "mint",
    tracks: [
      { title: "What You Know", artist: "Two Door Cinema Club", file: "audio/01.mp3" },
      { title: "Sete", artist: "BLOND:ISH, Francis Mercier, Amadou & Mariam", file: "audio/02.mp3" },
      { title: "You Will See", artist: "Quarterhead, SESA", file: "audio/03.mp3" },
      { title: "La leçon particulière", artist: "Lavern, Francis Lai", file: "audio/04.mp3" },
      { title: "She’s Gone, Dance On", artist: "Disclosure", file: "audio/05.mp3" },
      { title: "Finder (Hope) - Radio Edit", artist: "Ninetoes, Fatboy Slim", file: "audio/06.mp3" },
      { title: "Blue Berries", artist: "Sem Jacobs, Tagmann", file: "audio/07.mp3" },
      { title: "Somethin' Here - Original Mix", artist: "Terrence Parker", file: "audio/08.mp3" },
      { title: "Dancing Thing", artist: "VisionV", file: "audio/09.mp3" },
      { title: "Check Out", artist: "J. Worra, Leo Stannard", file: "audio/10.mp3" },
      { title: "Turn Around - Radio Edit", artist: "Phats & Small, Toney Lee", file: "audio/11.mp3" },
      { title: "Move Your Body", artist: "Marshall Jefferson, Solardo", file: "audio/12.mp3" },
      { title: "Too Easy", artist: "Connor Price, Nic D", file: "audio/13.mp3" },
      { title: "Love Lost", artist: "Mac Miller, The Temper Trap", file: "audio/14.mp3" },
      { title: "12 to 12", artist: "sombr", file: "audio/15.mp3" },
      { title: "Hope", artist: "CAMELPHAT, Max Milner", file: "audio/16.mp3" },
      { title: "Holding Out for a Hero - Single Version", artist: "Bonnie Tyler", file: "audio/17.mp3" },
      { title: "Money For Nothing - Remastered 1996", artist: "Dire Straits", file: "audio/18.mp3" },
      { title: "Memory Lane", artist: "Fahlberg", file: "audio/19.mp3" },
      { title: "QUE CE SOIT CLAIR", artist: "Paul Kalkbrenner, Stromae", file: "audio/20.mp3" },
      { title: "Positive", artist: "Jamback", file: "audio/21.mp3" },
      { title: "Runnin' (Lose It All)", artist: "Naughty Boy, Beyoncé, Arrow Benjamin", file: "audio/22.mp3" },
      { title: "Won't Forget You (Edit)", artist: "Shouse", file: "audio/23.mp3" },
      { title: "Control", artist: "Emmit Fenn", file: "audio/24.mp3" },
      { title: "Livre Pra Voar - Radio Edit", artist: "Samantha Machado, Claudinho Brasil", file: "audio/25.mp3" },
      { title: "God Made Me Phunky - Jess Bays Remix", artist: "MD X-Spress, Jess Bays", file: "audio/26.mp3" },
      { title: "Ferrari", artist: "James Hype, Miggy Dela Rosa", file: "audio/27.mp3" },
      { title: "Peanut Butter Jelly", artist: "Galantis", file: "audio/28.mp3" },
      { title: "Adieu", artist: "Tchami", file: "audio/29.mp3" },
      { title: "Stay", artist: "FISHER", file: "audio/30.mp3" },
      { title: "Bo Bom - Alan Dixon Remix", artist: "Moeaike, Alan Dixon", file: "audio/31.mp3" },
      { title: "Lovesong", artist: "Super Flu", file: "audio/32.mp3" },
      { title: "Phoenix", artist: "Daft Punk", file: "audio/33.mp3" },
      { title: "Stupidisco - Radio Edit", artist: "Junior Jack", file: "audio/34.mp3" },
      { title: "Believe", artist: "Super Flu", file: "audio/35.mp3" },
    ],
  },
];
