window.PLAYLISTS = [
  {
    id: "special",
    name: "Midnight Runners",
    subtitle: "Special playlist · 35 tracks",
    accent: "mint",
    tracks: [
      { title: "What You Know", artist: "Two Door Cinema Club" },
      { title: "Sete", artist: "BLOND:ISH, Francis Mercier, Amadou & Mariam" },
      { title: "You Will See", artist: "Quarterhead, SESA" },
      { title: "La leçon particulière", artist: "Lavern, Francis Lai" },
      { title: "She’s Gone, Dance On", artist: "Disclosure" },
      { title: "Finder (Hope) - Radio Edit", artist: "Ninetoes, Fatboy Slim" },
      { title: "Blue Berries", artist: "Sem Jacobs, Tagmann" },
      { title: "Somethin' Here - Original Mix", artist: "Terrence Parker" },
      { title: "Dancing Thing", artist: "VisionV" },
      { title: "Check Out", artist: "J. Worra, Leo Stannard" },
      { title: "Turn Around - Radio Edit", artist: "Phats & Small, Toney Lee" },
      { title: "Move Your Body", artist: "Marshall Jefferson, Solardo" },
      { title: "Too Easy", artist: "Connor Price, Nic D" },
      { title: "Love Lost", artist: "Mac Miller, The Temper Trap" },
      { title: "12 to 12", artist: "sombr" },
      { title: "Hope", artist: "CAMELPHAT, Max Milner" },
      { title: "Holding Out for a Hero - Single Version", artist: "Bonnie Tyler" },
      { title: "Money For Nothing - Remastered 1996", artist: "Dire Straits" },
      { title: "Memory Lane", artist: "Fahlberg" },
      { title: "QUE CE SOIT CLAIR", artist: "Paul Kalkbrenner, Stromae" },
      { title: "Positive", artist: "Jamback" },
      { title: "Runnin' (Lose It All)", artist: "Naughty Boy, Beyoncé, Arrow Benjamin" },
      { title: "Won't Forget You (Edit)", artist: "Shouse" },
      { title: "Control", artist: "Emmit Fenn" },
      { title: "Livre Pra Voar - Radio Edit", artist: "Samantha Machado, Claudinho Brasil" },
      { title: "God Made Me Phunky - Jess Bays Remix", artist: "MD X-Spress, Jess Bays" },
      { title: "Ferrari", artist: "James Hype, Miggy Dela Rosa" },
      { title: "Peanut Butter Jelly", artist: "Galantis" },
      { title: "Adieu", artist: "Tchami" },
      { title: "Stay", artist: "FISHER" },
      { title: "Bo Bom - Alan Dixon Remix", artist: "Moeaike, Alan Dixon" },
      { title: "Lovesong", artist: "Super Flu" },
      { title: "Phoenix", artist: "Daft Punk" },
      { title: "Stupidisco - Radio Edit", artist: "Junior Jack" },
      { title: "Believe", artist: "Super Flu" },
    ],
  },
  {
    id: "tabata",
    name: "Tabata",
    subtitle: "Tabata Songs · 100 tracks",
    accent: "orange",
    tracks: [
      { title: "End of Beginning (Tabata)", artist: "Tabata Songs" },
      { title: "One More Night (Tabata)", artist: "Tabata Songs" },
      { title: "Cake by the Ocean (Tabata)", artist: "Tabata Songs" },
      { title: "Don't Stop the Music (Tabata)", artist: "Tabata Songs" },
      { title: "Mi Gente", artist: "Tabata Songs" },
      { title: "Stereo Love - Tabata", artist: "Tabata Songs" },
      { title: "Ain't No Mountain High Enough (Tabata)", artist: "Tabata Songs" },
      { title: "Still D.R.E. (Tabata)", artist: "Tabata Songs" },
      { title: "A Sky Full of Stars (Tabata)", artist: "Tabata Songs" },
      { title: "Body (Tabata)", artist: "Tabata Songs" },
      { title: "Closer (Tabata)", artist: "Tabata Songs" },
      { title: "There's Nothing Holdin' Me Back (Tabata)", artist: "Tabata Songs" },
      { title: "Physical (Tabata)", artist: "Tabata Songs" },
      { title: "Espresso (Tabata)", artist: "Tabata Songs" },
      { title: "Killing in the Name (Tabata)", artist: "Tabata Songs" },
      { title: "We Found Love (Tabata)", artist: "Tabata Songs" },
      { title: "Fireflies - Tabata", artist: "Tabata Songs" },
      { title: "Rocky (Tabata)", artist: "Tabata Songs" },
      { title: "Get Lucky (Tabata)", artist: "Tabata Songs" },
      { title: "I Gotta Feeling (Tabata)", artist: "Tabata Songs" },
      { title: "Crazy in Love (Tabata)", artist: "Tabata Songs" },
      { title: "Golden (Tabata)", artist: "Tabata Songs, Tabata Kids" },
      { title: "Watermelon Sugar (Tabata)", artist: "Tabata Songs, Dom Lewis" },
      { title: "Dance Monkey (Tabata)", artist: "Tabata Songs" },
      { title: "I Will Survive (Tabata)", artist: "Tabata Songs" },
      { title: "Blinding Lights (Tabata)", artist: "Tabata Songs" },
      { title: "As it Was (Tabata)", artist: "Tabata Songs" },
      { title: "Uptown Funk", artist: "Tabata Songs" },
      { title: "Blinding Lights (Tabata) [Spanish Version]", artist: "Tabata Songs" },
      { title: "Hymn for the Weekend (Tabata)", artist: "Tabata Songs" },
      { title: "Walk This Way (Tabata)", artist: "Tabata Songs" },
      { title: "Good 4 U (Tabata)", artist: "Tabata Songs" },
      { title: "Riptide - Tabata", artist: "Tabata Songs, Driscoll & Co" },
      { title: "Mr. Brightside (Tabata)", artist: "Tabata Songs" },
      { title: "Memories (Tabata)", artist: "Tabata Songs" },
      { title: "Despechá (Tabata)", artist: "Tabata Songs" },
      { title: "Crazy (Tabata)", artist: "Tabata Songs" },
      { title: "Eye of the Tiger (Tabata)", artist: "Tabata Songs" },
      { title: "Shake it Off (Tabata)", artist: "Tabata Songs" },
      { title: "I Wanna Dance with Somebody (Tabata)", artist: "Tabata Songs" },
      { title: "Houdini (Tabata)", artist: "Tabata Songs" },
      { title: "Birds of a Feather (Tabata)", artist: "Tabata Songs" },
      { title: "September (Tabata)", artist: "Tabata Songs" },
      { title: "Moves Like Jagger (Tabata)", artist: "Tabata Songs" },
      { title: "Don't Start Now (Tabata)", artist: "Tabata Songs" },
      { title: "Seven Nation Army (Tabata)", artist: "Tabata Songs" },
      { title: "Training Season (Tabata)", artist: "Tabata Songs" },
      { title: "Si Antes Te Hubiera Conocido (Tabata)", artist: "Tabata Songs" },
      { title: "Eastside (Tabata)", artist: "Tabata Songs" },
      { title: "Who (Tabata)", artist: "Tabata Songs" },
      { title: "Tell Me You Love Me (Tabata)", artist: "Tabata Songs" },
      { title: "I'm Shipping Up To Boston (Tabata)", artist: "Tabata Songs" },
      { title: "Can't Stop (Tabata)", artist: "Tabata Songs" },
      { title: "The Hey Song (Tabata)", artist: "Tabata Songs" },
      { title: "Greedy (Tabata)", artist: "Tabata Songs" },
      { title: "Heaven (Tabata)", artist: "Tabata Songs" },
      { title: "Last Last (Tabata)", artist: "Tabata Songs" },
      { title: "Blue (Da Ba Dee) Tabata", artist: "Tabata Songs" },
      { title: "Calm Down (Tabata)", artist: "Tabata Songs" },
      { title: "Higher Love (Tabata)", artist: "Tabata Songs" },
      { title: "Water (Tabata)", artist: "Tabata Songs" },
      { title: "Dance the Night (Tabata)", artist: "Tabata Songs" },
      { title: "Starboy (Tabata)", artist: "Tabata Songs" },
      { title: "Flowers", artist: "Tabata Songs" },
      { title: "Poker Face (Tabata)", artist: "Tabata Songs" },
      { title: "Casualty (Tabata)", artist: "Tabata Songs" },
      { title: "Shape of You (Tabata)", artist: "Tabata Songs" },
      { title: "Thriller - Tabata", artist: "Tabata Songs" },
      { title: "Pump Up the Jam (Tabata)", artist: "Tabata Songs" },
      { title: "Can't Stop the Feeling - Tabata Version", artist: "Tabata Songs, John Wayno" },
      { title: "Shivers (Tabata)", artist: "Tabata Songs" },
      { title: "Viva La Vida (Tabata)", artist: "Tabata Songs" },
      { title: "Wonderwall (Tabata)", artist: "Tabata Songs" },
      { title: "Bad Habits (Tabata)", artist: "Tabata Songs" },
      { title: "Toxic - Tabata", artist: "Tabata Songs" },
      { title: "Seven (Tabata)", artist: "Tabata Songs" },
      { title: "...Baby One More Time (Tabata)", artist: "Tabata Songs" },
      { title: "Light Switch (Tabata)", artist: "Tabata Songs" },
      { title: "Something Just Like This (Tabata)", artist: "Tabata Songs" },
      { title: "Take on Me (Tabata)", artist: "Tabata Songs" },
      { title: "Sunflower (Tabata)", artist: "Tabata Songs" },
      { title: "Carry On Wayward Son (Tabata)", artist: "Tabata Songs" },
      { title: "Song 2 (Tabata)", artist: "Tabata Songs" },
      { title: "Break My Heart (Tabata)", artist: "Tabata Songs" },
      { title: "Happy (Tabata)", artist: "Tabata Songs" },
      { title: "Despacito (Tabata)", artist: "Tabata Songs" },
      { title: "Fast Car (Tabata)", artist: "Tabata Songs" },
      { title: "Run (Tabata)", artist: "Tabata Songs" },
      { title: "Cheap Thrills (Tabata)", artist: "Tabata Songs" },
      { title: "Lose Yourself (Tabata)", artist: "Tabata Songs" },
      { title: "Running Up That Hill (Tabata)", artist: "Tabata Songs" },
      { title: "Sacrifice (Tabata)", artist: "Tabata Songs" },
      { title: "DÁKITI (Tabata)", artist: "Tabata Songs" },
      { title: "Loco Contigo", artist: "Tabata Songs" },
      { title: "Rather Be (Tabata)", artist: "Tabata Songs" },
      { title: "Danza Kuduro", artist: "Tabata Songs" },
      { title: "Forever Yours (Tabata)", artist: "Tabata Songs" },
      { title: "Me Gusta (Tabata)", artist: "Tabata Songs" },
      { title: "Cold Heart (Tabata)", artist: "Tabata Songs" },
      { title: "Dynamite (Tabata)", artist: "Tabata Songs" },
    ],
  },
];
